import { createClient } from "npm:@supabase/supabase-js@2";
import webpush from "npm:web-push@3.6.7";
const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS"};
const out=(v:unknown,s=200)=>new Response(JSON.stringify(v),{status:s,headers:{...cors,"Content-Type":"application/json"}});
Deno.serve(async req=>{
 if(req.method==="OPTIONS")return new Response("ok",{headers:cors});if(req.method!=="POST")return out({error:"Method not allowed"},405);
 const url=Deno.env.get("SUPABASE_URL")||"",anon=Deno.env.get("SUPABASE_ANON_KEY")||"",key=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")||"",pub=Deno.env.get("VAPID_PUBLIC_KEY")||"",priv=Deno.env.get("VAPID_PRIVATE_KEY")||"",subject=Deno.env.get("VAPID_SUBJECT")||"mailto:admin@example.com";if(![url,anon,key,pub,priv].every(Boolean))return out({error:"Missing secrets"},500);
 const token=(req.headers.get("Authorization")||"").replace(/^Bearer\s+/i,"");if(!token)return out({error:"Authentication required"},401);
 const uc=createClient(url,anon,{global:{headers:{Authorization:`Bearer ${token}`}}}),{data:ud,error:ue}=await uc.auth.getUser(token);if(ue||!ud.user)return out({error:"Invalid session"},401);
 const db=createClient(url,key,{auth:{persistSession:false,autoRefreshToken:false}}),{data:p}=await db.from("perfiles").select("rol,activo").eq("id",ud.user.id).maybeSingle();if(!p?.activo||!["recepcion","administracion","gerencia","sysadmin","system_admin"].includes(String(p.rol).toLowerCase()))return out({error:"Not authorized"},403);
 let body:{reserva_id?:string};try{body=await req.json()}catch{return out({error:"Invalid JSON"},400)}if(!body.reserva_id)return out({error:"reserva_id required"},400);
 const {data:r,error:re}=await db.from("reservas").select("id,estado,unidades(codigo,edificios(nombre))").eq("id",body.reserva_id).maybeSingle();if(re||!r)return out({error:"Reservation not found"},404);if(r.estado!=="check_out")return out({error:"Reservation is not checked out"},409);
 const {data:cl,error:ce}=await db.from("perfiles").select("id").eq("activo",true).eq("rol","limpieza");if(ce)return out({error:ce.message},500);const ids=(cl||[]).map((x:{id:string})=>x.id);if(!ids.length)return out({sent:0});const {data:subs,error:se}=await db.from("push_subscriptions").select("id,subscription").in("user_id",ids);if(se)return out({error:se.message},500);
 const u=Array.isArray(r.unidades)?r.unidades[0]:r.unidades,b=Array.isArray(u?.edificios)?u.edificios[0]:u?.edificios;webpush.setVapidDetails(subject,pub,priv);let sent=0;const stale:string[]=[];await Promise.all((subs||[]).map(async(x:{id:string;subscription:Record<string,unknown>})=>{try{await webpush.sendNotification(x.subscription as never,JSON.stringify({title:"Unidad lista para limpieza",body:`${b?.nombre||"Edificio"} · Unidad ${u?.codigo||"—"} quedó libre tras el check-out.`,tag:`limpieza-${r.id}`,url:"./"}));sent++}catch(e){const c=(e as {statusCode?:number})?.statusCode;if(c===404||c===410)stale.push(x.id);else console.error(e)}}));if(stale.length)await db.from("push_subscriptions").delete().in("id",stale);return out({sent,stale:stale.length});
});
